directory: ../music
library: ./library.db
import:
  copy: no
  move: no
  write: no
  autotag: no
pluginpath:
    - src/beetsplug
plugins: duplicates duplicatez
duplicates:
  album: no
  copy: none
  count: no
  delete: no
  format: $mb_trackid - $mb_albumid | $path
  full: yes
  strict: yes
  move: none
  keys: [mb_trackid, mb_albumid]
  path: no
  group: no